# Generated by Django 6.0.2 on 2026-02-14 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Scholarship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("organization", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("eligibility", models.TextField(blank=True)),
                ("deadline", models.DateField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("funding_amount", models.CharField(blank=True, max_length=100)),
                ("link", models.URLField(blank=True)),
                ("is_approved", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("source_url", models.URLField(blank=True)),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
                ("mongo_id", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "scholarships",
                "indexes": [
                    models.Index(
                        fields=["is_approved", "is_active"],
                        name="scholarship_is_appr_ab0c85_idx",
                    ),
                    models.Index(
                        fields=["deadline"], name="scholarship_deadlin_aa68a6_idx"
                    ),
                    models.Index(
                        fields=["country"], name="scholarship_country_2285c7_idx"
                    ),
                    models.Index(fields=["title"], name="scholarship_title_2afd95_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scholarship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="scholarships.scholarship",
                    ),
                ),
            ],
            options={
                "db_table": "bookmarks",
                "indexes": [
                    models.Index(fields=["user"], name="bookmarks_user_id_687ca2_idx")
                ],
                "unique_together": {("user", "scholarship")},
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("submitted", "Submitted"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scholarship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="scholarships.scholarship",
                    ),
                ),
            ],
            options={
                "db_table": "applications",
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="application_user_id_4cfcce_idx"
                    ),
                    models.Index(
                        fields=["scholarship"], name="application_scholar_9a8908_idx"
                    ),
                ],
                "unique_together": {("user", "scholarship")},
            },
        ),
    ]
