# Generated by Django 6.0.2 on 2026-02-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Career",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("required_skills", models.JSONField(blank=True, default=list)),
                (
                    "average_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("growth_rate", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "careers",
                "indexes": [
                    models.Index(fields=["name"], name="careers_name_ceebdd_idx"),
                    models.Index(
                        fields=["category"], name="careers_categor_06b8e1_idx"
                    ),
                ],
            },
        ),
    ]
