# Generated by Django 6.0.2 on 2026-02-14 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("careers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelTrainingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=50)),
                ("accuracy", models.DecimalField(decimal_places=4, max_digits=5)),
                ("precision", models.DecimalField(decimal_places=4, max_digits=5)),
                ("recall", models.DecimalField(decimal_places=4, max_digits=5)),
                (
                    "f1_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                ("training_samples", models.IntegerField()),
                ("model_file_path", models.CharField(blank=True, max_length=500)),
                ("trained_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "model_training_history",
                "ordering": ["-trained_at"],
            },
        ),
        migrations.CreateModel(
            name="CareerRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(decimal_places=4, max_digits=5),
                ),
                ("model_used", models.CharField(blank=True, max_length=50)),
                ("rank", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "career",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="careers.career",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "career_recommendations",
                "indexes": [
                    models.Index(
                        fields=["user", "rank"], name="career_reco_user_id_ae1a06_idx"
                    )
                ],
                "unique_together": {("user", "career", "rank")},
            },
        ),
    ]
