# Generated by Django 6.0.2 on 2026-02-14 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gpa",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("degree_level", models.CharField(blank=True, max_length=50)),
                ("major", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("target_country", models.CharField(blank=True, max_length=100)),
                (
                    "ielts_score",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("toefl_score", models.IntegerField(blank=True, null=True)),
                ("gre_score", models.IntegerField(blank=True, null=True)),
                ("gmat_score", models.IntegerField(blank=True, null=True)),
                ("income_range", models.CharField(blank=True, max_length=50)),
                ("need_based_preference", models.BooleanField(default=False)),
                ("technical_skills", models.JSONField(blank=True, default=list)),
                ("soft_skills", models.JSONField(blank=True, default=list)),
                ("interests", models.JSONField(blank=True, default=list)),
                ("holland_code", models.CharField(blank=True, max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "profiles",
                "indexes": [
                    models.Index(fields=["user"], name="profiles_user_id_29277a_idx"),
                    models.Index(
                        fields=["country", "target_country"],
                        name="profiles_country_75dfbd_idx",
                    ),
                ],
            },
        ),
    ]
