# Generated by Django 6.0.2 on 2026-02-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_profile_profile_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountryOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "country_options",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MajorOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "major_options",
                "ordering": ["name"],
            },
        ),
    ]
